export const speedList = [
  { value: "slow", label: "Slow" },
  { value: "medium", label: "Medium" },
  { value: "fast", label: "Fast" },
];

export const modeList = [
  { value: "easy", label: "Easy" },
  { value: "normal", label: "Normal" },
  { value: "hard", label: "Hard" },
  { value: "expert", label: "Expert" },
  { value: "insane", label: "Insane" },
  { value: "nightmare", label: "Nightmare" },
];

export const itemsListOne = [
  { value: "item1", label: "Item 1" },
  { value: "item2", label: "Item 2" },
  { value: "item3", label: "Item 3" },
  { value: "item4", label: "Item 4" },
  { value: "item5", label: "Item 5" },
  { value: "item6", label: "Item 6" },
];

export const colorsList = [
  { value: "red", label: "Red" },
  { value: "green", label: "Green" },
  { value: "blue", label: "Blue" },
  { value: "yellow", label: "Yellow" },
  { value: "purple", label: "Purple" },
  { value: "orange", label: "Orange" },
];

export const randomWordsList = [
  {value: "abyss", label: "Abyss"},
  {value: "alien", label: "Alien"},
  {value: "apocalypse", label: "Apocalypse"},
  {value: "arena", label: "Arena"},
  {value: "assault", label: "Assault"},
  {value: "battle", label: "Battle"},
  {value: "blast", label: "Blast"},
  {value: "blitz", label: "Blitz"},
  {value: "blood", label: "Blood"},
  {value: "brawl", label: "Brawl"},
  {value: "chaos", label: "Chaos"},
  {value: "clash", label: "Clash"},
  {value: "combat", label: "Combat"},
  {value: "conflict", label: "Conflict"},
  {value: "conquest", label: "Conquest"},
  {value: "crisis", label: "Crisis"},
  {value: "crusade", label: "Crusade"},
  {value: "curse", label: "Curse"},
  {value: "darkness", label: "Darkness"},
  {value: "dawn", label: "Dawn"},
  {value: "death", label: "Death"},
  {value: "defeat", label: "Defeat"},
  {value: "demon", label: "Demon"},
  {value: "despair", label: "Despair"},
  {value: "destruction", label: "Destruction"},
  {value: "devil", label: "Devil"},
  {value: "doom", label: "Doom"},
  {value: "dragon", label: "Dragon"},
  {value: "dream", label: "Dream"},
  {value: "dungeon", label: "Dungeon"},
  {value: "eclipse", label: "Eclipse"},
  {value: "empire", label: "Empire"},
  {value: "end", label: "End"},
  {value: "epic", label: "Epic"},
  {value: "evil", label: "Evil"},
  {value: "fate", label: "Fate"},
  {value: "fear", label: "Fear"},
  {value: "fight", label: "Fight"},
  {value: "fire", label: "Fire"},
  {value: "flame", label: "Flame"},
  {value: "force", label: "Force"},
  {value: "fortress", label: "Fortress"},
  {value: "fury", label: "Fury"},
  {value: "future", label: "Future"},
  {value: "galaxy", label: "Galaxy"},
  {value: "glory", label: "Glory"},
  {value: "god", label: "God"},
  {value: "guardian", label: "Guardian"},
  {value: "gun", label: "Gun"},
  {value: "havoc", label: "Havoc"},
  {value: "hell", label: "Hell"},
  {value: "hero", label: "Hero"},
  {value: "horror", label: "Horror"},
  {value: "infinity", label: "Infinity"},
  {value: "justice", label: "Justice"},
  {value: "king", label: "King"},
  {value: "knight", label: "Knight"},
  {value: "legend", label: "Legend"},
  {value: "legacy", label: "Legacy"},
  {value: "life", label: "Life"},
  {value: "light", label: "Light"},
  {value: "magic", label: "Magic"},
  {value: "master", label: "Master"},
  {value: "might", label: "Might"},
  {value: "monster", label: "Monster"},
  {value: "mystery", label: "Mystery"},
  {value: "night", label: "Night"},
  {value: "ninja", label: "Ninja"},
  {value: "oblivion", label: "Oblivion"},
  {value: "panic", label: "Panic"},
  {value: "pirate", label: "Pirate"},
  {value: "power", label: "Power"},
  {value: "quest", label: "Quest"},
  {value: "rage", label: "Rage"},
  {value: "rebel", label: "Rebel"},
  {value: "revenge", label: "Revenge"},
  {value: "rise", label: "Rise"},
  {value: "rogue", label: "Rogue"},
  {value: "ruin", label: "Ruin"},
  {value: "run", label: "Run"},
  {value: "savage", label: "Savage"},
  {value: "shadow", label: "Shadow"},
  {value: "soul", label: "Soul"},
  {value: "space", label: "Space"},
  {value: "spirit", label: "Spirit"},
  {value: "star", label: "Star"},
  {value: "storm", label: "Storm"},
  {value: "strike", label: "Strike"},
  {value: "survival", label: "Survival"},
  {value: "terror", label: "Terror"},
  {value: "thunder", label: "Thunder"},
  {value: "titan", label: "Titan"},
  {value: "tomb", label: "Tomb"},
  {value: "tornado", label: "Tornado"},
  {value: "tower", label: "Tower"},
  {value: "treasure", label: "Treasure"},
  {value: "tribe", label: "Tribe"},
  {value: "twilight", label: "Twilight"},
  {value: "ultimate", label: "Ultimate"},
  {value: "valley", label: "Valley"},
  {value: "vengeance", label: "Vengeance"},
  {value: "victory", label: "Victory"},
  {value: "war", label: "War"},
  {value: "warrior", label: "Warrior"},
  {value: "wild", label: "Wild"},
  {value: "witch", label: "Witch"},
  {value: "wizard", label: "Wizard"},
];

